package com.atlantbh.auction.seeder;

import com.atlantbh.auction.model.*;
import com.atlantbh.auction.repository.AddressRepository;
import com.atlantbh.auction.repository.ProductRepository;
import com.atlantbh.auction.repository.UserRepository;
import com.sun.istack.logging.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.*;
import java.util.logging.Level;

@Component
@Order(1)
public class DataSeeder implements CommandLineRunner {

    private static final Logger LOGGER = Logger.getLogger(DataSeeder.class);

    @Autowired
    ProductRepository productRepository;
    @Autowired
    private UserRepository userRepository;
    @Autowired
    private AddressRepository addressRepository;

    private LocalDateTime dateTime;

    public DataSeeder(ProductRepository productRepository) {
        this.productRepository = productRepository;
    }

    @Override
    public void run(String... args) throws Exception {
        if (userRepository.findAll() != null && addressRepository.findAll() != null && productRepository.findAll() != null) {

            List<Product> listOfProducts = new ArrayList<>();
            Set<Category> setOfCategories = new HashSet<>();
            List<Address> listOfAddresses = new ArrayList<>();
            List<User> listOfUsers = new ArrayList<>();


            Category fashion = new Category("Fashion");
            Category accessories = new Category("Accessories");
            Category jewelery = new Category("Jewelery");
            Category shoes = new Category("Shoes");
            Category sportware = new Category("Sportware");
            Category home = new Category("Home");
            Category electronics = new Category("Electronics");
            Category mobile = new Category("Mobile");
            Category computer = new Category("Computer");
            Category tools = new Category("Tools");
            Category books = new Category("Books");

            SubCategory subcategory1 = new SubCategory("Wedding", fashion);
            SubCategory subcategory2 = new SubCategory("Clothes", fashion);
            subcategory2.setPhotoUrl("https://images.unsplash.com/photo-1512436991641-6745cdb1723f?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEyMDd9");
            SubCategory subcategory12 = new SubCategory("Coats", fashion);
            SubCategory subcategory13 = new SubCategory("Vintage", fashion);
            SubCategory subcategory14 = new SubCategory("Cool", fashion);
            SubCategory subcategory4 = new SubCategory("Swimming", fashion);
            SubCategory subcategory8 = new SubCategory("Watches", accessories);
            subcategory8.setPhotoUrl("https://preview.redd.it/zfegrkerlk031.jpg?width=960&crop=smart&auto=webp&s=77f929c834026b75567d63acce85c65e611765d2");
            SubCategory subcategory15 = new SubCategory("Sunglasses", accessories);
            SubCategory subcategory16 = new SubCategory("Swimming glasses", accessories);
            SubCategory subcategory17 = new SubCategory("Wristbands", accessories);
            SubCategory subcategory18 = new SubCategory("Hats", accessories);
            SubCategory subcategory19 = new SubCategory("Bags", accessories);
            SubCategory subcategory9 = new SubCategory("Necklaces", jewelery);
            subcategory9.setPhotoUrl("https://marianilsdotter.com/wp-content/uploads/2020/05/categorypage-necklaces-mobile.jpg");
            SubCategory subCategory10 = new SubCategory("Rings", jewelery);
            SubCategory subCategory21 = new SubCategory("Rings", jewelery);
            SubCategory subCategory22 = new SubCategory("Hairpin", jewelery);
            SubCategory subCategory23 = new SubCategory("Bracelet", jewelery);
            SubCategory subCategory24 = new SubCategory("Body Piercing jewelery", jewelery);
            SubCategory subcategory5 = new SubCategory("Casual shoes", shoes);
            SubCategory subcategory11 = new SubCategory("Running shoes", shoes);
            subcategory11.setPhotoUrl("https://www.saucony.com/on/demandware.static/-/Sites-saucony_us-Library/default/dwb7a76b30/content/seasonal-content/homepage/2020/10/home-main-trending-20201001-prinkshop-mens-d.jpg");
            SubCategory subcategory25 = new SubCategory("Hiking shoes", shoes);
            SubCategory subcategory26 = new SubCategory("Winter runningShoes4", shoes);
            SubCategory subcategory27 = new SubCategory("Classy shoes", shoes);
            SubCategory subcategory28 = new SubCategory("Summer shoes", shoes);
            SubCategory subcategory20 = new SubCategory("Sport shorts", sportware);
            SubCategory subcategory29 = new SubCategory("Training clothes", sportware);
            subcategory29.setPhotoUrl("https://ae01.alicdn.com/kf/H9ee1ae499a3441bea2f3c3295c79da97f/Running-Training-Clothes-Men-7PCS-SETS-Compression-Running-Sets-Basketball-Jogging-Tights-Underwear-Set-Gym-Fitness.jpg_960x960.jpg");
            SubCategory subcategory30 = new SubCategory("Tank tops", sportware);
            SubCategory subcategory31 = new SubCategory("Gym accessories", sportware);
            SubCategory subcategory32 = new SubCategory("Women clothes", sportware);
            SubCategory subcategory33 = new SubCategory("Hijabi sportwear", sportware);
            SubCategory subcategory3 = new SubCategory("Bad & Bath", home);
            SubCategory subcategory34 = new SubCategory("Bedroom", home);
            subcategory34.setPhotoUrl("https://www.yankodesign.com/images/design_news/2020/06/bedroom-designs/07-bedroom-Designs_Natural-Lighting_Berlin-HOuse.jpg");
            SubCategory subcategory35 = new SubCategory("Kitchen", home);
            SubCategory subcategory36 = new SubCategory("Living room", home);
            SubCategory subcategory37 = new SubCategory("Kids room", home);
            SubCategory subcategory38 = new SubCategory("Balcony", home);
            SubCategory subCategory39 = new SubCategory("Kitchen electronics", electronics);
            subCategory39.setPhotoUrl("https://mydecorative.com/wp-content/uploads/2019/05/new-refrigerator.jpg");
            SubCategory subCategory40 = new SubCategory("TVs", electronics);
            SubCategory subCategory41 = new SubCategory("Lamps", electronics);
            SubCategory subCategory42 = new SubCategory("Gaming consoles", electronics);
            SubCategory subCategory43 = new SubCategory("Washing machines", electronics);
            SubCategory subCategory44 = new SubCategory("Air conditioning", electronics);
            SubCategory subcategory6 = new SubCategory("Phones", mobile);
            subcategory6.setPhotoUrl("https://cdn.pocket-lint.com/r/s/1200x/assets/images/120309-phones-buyer-s-guide-best-smartphones-2020-the-top-mobile-phones-available-to-buy-today-image1-eagx1ykift.jpg");
            SubCategory subcategory45 = new SubCategory("Chargers", mobile);
            SubCategory subcategory46 = new SubCategory("Headphones", mobile);
            SubCategory subcategory47 = new SubCategory("Masks", mobile);
            SubCategory subcategory48 = new SubCategory("Cases", mobile);
            SubCategory subcategory49 = new SubCategory("Screen protectors", mobile);
            SubCategory subcategory7 = new SubCategory("Laptops", computer);
            subcategory7.setPhotoUrl("https://cdn.mos.cms.futurecdn.net/X5TyA8uvkGXoNyjFzxcowS.jpg");
            SubCategory subcategory50 = new SubCategory("Gaming computers", computer);
            SubCategory subcategory51 = new SubCategory("Office computers", computer);
            SubCategory subcategory52 = new SubCategory("Hardware", computer);
            SubCategory subcategory53 = new SubCategory("Software", computer);
            SubCategory subcategory54 = new SubCategory("Monitors", computer);
            SubCategory subcategory55 = new SubCategory("Drills", tools);
            SubCategory subcategory56 = new SubCategory("Wrenches", tools);
            SubCategory subcategory57 = new SubCategory("Measuring tapes", tools);
            SubCategory subcategory58 = new SubCategory("Hand tools", tools);
            subcategory58.setPhotoUrl("https://cdn1.vectorstock.com/i/1000x1000/89/80/modern-hand-tools-instruments-collection-vector-2148980.jpg");
            SubCategory subcategory59 = new SubCategory("Knives", tools);
            SubCategory subcategory60 = new SubCategory("Screwdrivers", tools);
            SubCategory subCategory61 = new SubCategory("Children books", books);
            SubCategory subCategory62 = new SubCategory("Motivational books", books);
            SubCategory subCategory63 = new SubCategory("SCIFI books", books);
            subCategory63.setPhotoUrl("https://media.wired.com/photos/5be4cd03db23f3775e466767/125:94/w_2375,h_1786,c_limit/books-521812297.jpg");
            SubCategory subCategory64 = new SubCategory("Romance books", books);
            SubCategory subCategory65 = new SubCategory("Cook books", books);
            SubCategory subCategory66 = new SubCategory("DIY Books", books);


            setOfCategories.add(fashion);
            setOfCategories.add(accessories);
            setOfCategories.add(jewelery);
            setOfCategories.add(shoes);
            setOfCategories.add(sportware);
            setOfCategories.add(home);
            setOfCategories.add(electronics);
            setOfCategories.add(mobile);
            setOfCategories.add(computer);
            setOfCategories.add(tools);
            setOfCategories.add(books);

            listOfAddresses.add(new Address("Vojvodica Put 3 ", "Zenica", "Bosnia & Herzegovina", "65262"));
            listOfAddresses.add(new Address("246 E Colden Ave", "Los Angeles", "US", "90003"));
            listOfAddresses.add(new Address("1648 W Ontario St", "Chicago", "US", "60622"));
            listOfAddresses.add(new Address("88 Station Road ", "London", "UK", "WC2N 5DU"));
            addressRepository.saveAll(listOfAddresses);

            listOfUsers.add(new User("Harun", "Hasic", "harunze@hotmail.com", "male", new Date("24/02/1998"), "062-679-679", new BCryptPasswordEncoder().encode("Harun123"), "/assets/images/profile1.jpg"));
            listOfUsers.add(new User("Tommy", "Jameson", "tommy@hotmail.com", "male", new Date("05/03/1985"), "062-123-456", new BCryptPasswordEncoder().encode("Tommy123"), "/assets/images/profile2.jpg"));
            listOfUsers.add(new User("Tom", "Hanks", "demo@tom.com", "male", new Date("05/02/1965"), "432-321-2345", new BCryptPasswordEncoder().encode("Tommy123"), "/assets/images/profile3.png"));
            listOfUsers.add(new User("Kleopatra", "Egipcanin", "kleopatra@democom", "female", new Date("22/02/1927"), "123-456-1231", new BCryptPasswordEncoder().encode("Tommy123"), "/assets/images/profile4.jpg"));
            listOfUsers.get(0).setAddress(listOfAddresses.get(0));
            listOfUsers.get(1).setAddress(listOfAddresses.get(1));
            listOfUsers.get(2).setAddress(listOfAddresses.get(2));
            listOfUsers.get(3).setAddress(listOfAddresses.get(3));
            userRepository.saveAll(listOfUsers);

            Set<Photo> runningShoes = new HashSet<>();
            Set<Photo> runningShoes2 = new HashSet<>();
            Set<Photo> runningShoes3 = new HashSet<>();
            Set<Photo> runningShoes4 = new HashSet<>();
            Set<Photo> iPhone11Pro = new HashSet<>();
            Set<Photo> iPhoneX = new HashSet<>();
            Set<Photo> iPhoneXr = new HashSet<>();
            Set<Photo> s20 = new HashSet<>();
            Set<Photo> hpG7 = new HashSet<>();
            Set<Photo> macbookPro = new HashSet<>();
            Set<Photo> lenovo = new HashSet<>();
            Set<Photo> dell = new HashSet<>();
            Set<Photo> bunkbed = new HashSet<>();
            Set<Photo> kingsize = new HashSet<>();
            Set<Photo> bed = new HashSet<>();
            Set<Photo> cover = new HashSet<>();
            Set<Photo> tissot = new HashSet<>();
            Set<Photo> rolex = new HashSet<>();
            Set<Photo> tagheuer = new HashSet<>();
            Set<Photo> omega = new HashSet<>();
            Set<Photo> goldenNecklace = new HashSet<>();
            Set<Photo> goldenPendant = new HashSet<>();
            Set<Photo> diamondVine = new HashSet<>();
            Set<Photo> rosePendant = new HashSet<>();
            Set<Photo> womansTracksuit = new HashSet<>();
            Set<Photo> mensTracksuit = new HashSet<>();
            Set<Photo> womenYoga = new HashSet<>();
            Set<Photo> menShorts = new HashSet<>();
            Set<Photo> builtInOven = new HashSet<>();
            Set<Photo> microwave = new HashSet<>();
            Set<Photo> washingMachine = new HashSet<>();
            Set<Photo> dishwasher = new HashSet<>();
            Set<Photo> suit = new HashSet<>();
            Set<Photo> dress = new HashSet<>();
            Set<Photo> hats = new HashSet<>();
            Set<Photo> sunglasses = new HashSet<>();
            Set<Photo> hammer = new HashSet<>();
            Set<Photo> cutter = new HashSet<>();
            Set<Photo> axe = new HashSet<>();
            Set<Photo> saw = new HashSet<>();
            Set<Photo> harryPotter = new HashSet<>();
            Set<Photo> theGodfather = new HashSet<>();
            Set<Photo> lotr = new HashSet<>();
            Set<Photo> hyperion = new HashSet<>();

            runningShoes.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/puma/thumbs_800/374011-01_800_800px.jpg", true));
            runningShoes.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/puma/thumbs_800/374011-01_1_800_800px.jpg", true));
            runningShoes.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/puma/thumbs_800/374011-01_3_800_800px.jpg", true));
            runningShoes.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/puma/thumbs_800/374011-01_4_800_800px.jpg", true));
            runningShoes2.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/nike/thumbs_800/CJ0611-100_800_800px.jpg", true));
            runningShoes2.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/nike/thumbs_800/CJ0611-100_1_800_800px.jpg", true));
            runningShoes2.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/nike/thumbs_800/CJ0611-100_2_800_800px.jpg", true));
            runningShoes2.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/nike/thumbs_800/CJ0611-100_4_800_800px.jpg", true));
            runningShoes3.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/adidas/thumbs_800/FX8834_800_800px.jpg", true));
            runningShoes3.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/adidas/thumbs_800/FX8834_1_800_800px.jpg", true));
            runningShoes3.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/adidas/thumbs_800/FX8834_3_800_800px.jpg", true));
            runningShoes3.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/adidas/thumbs_800/FX8834_4_800_800px.jpg", true));
            runningShoes4.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/no-name-brand/thumbs_800/3022590-600_800_800px.jpg", true));
            runningShoes4.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/no-name-brand/thumbs_800/3022590-600_1_800_800px.jpg", true));
            runningShoes4.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/no-name-brand/thumbs_800/3022590-600_2_800_800px.jpg", true));
            runningShoes4.add(new Photo("https://www.buzzsneakers.com/files/thumbs/files/images/product/brand/no-name-brand/thumbs_800/3022590-600_4_800_800px.jpg", true));
            iPhone11Pro.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/10/iPhone11ProMAX8.jpg", true));
            iPhone11Pro.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/10/iPhone11ProMAX7.jpg", true));
            iPhone11Pro.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/10/iPhone11ProMAX9.jpg", true));
            iPhone11Pro.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/10/iPhone11ProMAX12.jpg", true));
            iPhoneX.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/06/apple_iphone_x_64gb10.jpg", true));
            iPhoneX.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/06/apple_iphone_x_64gb3.jpg", true));
            iPhoneX.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/06/apple_iphone_x_64gb4.jpg", true));
            iPhoneX.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/06/apple_iphone_x_64gb5.jpg", true));
            iPhoneXr.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/02/apple_iphone_xr_128gb_30907883201-1.jpg", true));
            iPhoneXr.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/02/apple_iphone_xr_128gb_30907883202-1.jpg", true));
            iPhoneXr.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/02/apple_iphone_xr_128gb_30907883203-1.jpg", true));
            iPhoneXr.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2019/02/apple_iphone_xr_128gb_30907883204-1.jpg", true));
            s20.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/03/samsungs20-1.jpg", true));
            s20.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/03/samsungs20-2.jpg", true));
            s20.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/03/samsungs20-5.jpg", true));
            s20.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/03/samsungs20-4.jpg", true));
            hpG7.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/hp450-1.jpg", true));
            hpG7.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/hp450-2.jpg", true));
            hpG7.add(new Photo("https://teranews.net/wp-content/uploads/2019/09/noutbuk-hp-250-g7-4.jpg", true));
            hpG7.add(new Photo("https://media.karousell.com/media/photos/products/2020/7/31/hp_probook_440_g7_i5_1596172518_fa03034b_progressive", true));
            macbookPro.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/08/macbooki9-9880H-1.jpg", true));
            macbookPro.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/08/macbooki9-9880H-2.jpg", true));
            macbookPro.add(new Photo("https://m.media-amazon.com/images/S/aplus-media/sota/d8afcb2e-7f37-4767-8611-136b3d25fb2e.__CR0,0,970,600_PT0_SX970_V1___.jpg", true));
            macbookPro.add(new Photo("https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6421/6421409_sd.jpg", true));
            lenovo.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/10/111.jpg", true));
            lenovo.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/10/2.png", true));
            lenovo.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/10/5.png", true));
            lenovo.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/10/6.png", true));
            dell.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/04/1-17.jpg", true));
            dell.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/04/2-17.jpg", true));
            dell.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/04/5-1.jpg", true));
            dell.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/04/6-1.jpg", true));
            bunkbed.add(new Photo("https://cdn2.jysk.com/getimage/wd2.large/98995", true));
            bunkbed.add(new Photo("https://cdn2.jysk.com/getimage/wd2.large/98996", true));
            bunkbed.add(new Photo("https://cdn2.jysk.com/getimage/wd2.large/98997", true));
            bunkbed.add(new Photo("https://cdn1.jysk.com/getimage/wd2.large/26751", true));
            kingsize.add(new Photo("https://cdn2.jysk.com/getimage/wd2.large/72282", true));
            kingsize.add(new Photo("https://cdn2.jysk.com/getimage/wd2.large/73576", true));
            kingsize.add(new Photo("https://cdn2.jysk.com/getimage/wd2.large/90538", true));
            kingsize.add(new Photo("https://cdn2.jysk.com/getimage/wd2.large/89935", true));
            bed.add(new Photo("https://cdn3.jysk.com/getimage/wd2.large/123942", true));
            bed.add(new Photo("https://cdn3.jysk.com/getimage/wd2.large/99020", true));
            bed.add(new Photo("https://cdn3.jysk.com/getimage/wd2.large/123943", true));
            bed.add(new Photo("https://cdn3.jysk.com/getimage/wd2.large/123944", true));
            cover.add(new Photo("https://cdn4.jysk.com/getimage/wd2.medium/107527", true));
            cover.add(new Photo("https://cdn4.jysk.com/getimage/wd2.medium/103803", true));
            cover.add(new Photo("https://media.sheridan.com.au/catalog/product/S/3/S3Y5_B113_C226-531_silver_1_1700x1700.jpg", true));
            cover.add(new Photo("https://secure.img1-fg.wfcdn.com/im/91949996/resize-h800-w800%5Ecompr-r85/4331/43310952/Vester+Reversible+Down+Alternative+Comforter+Set.jpg", true));
            tissot.add(new Photo("https://d1rkccsb0jf1bk.cloudfront.net/products/99998437/main/large/t106_417_11_051_00-1460379836-2948.jpg", true));
            tissot.add(new Photo("https://d1rkccsb0jf1bk.cloudfront.net/products/99998437/additional/large/99998437-2.jpg", true));
            tissot.add(new Photo("https://d1rkccsb0jf1bk.cloudfront.net/products/99998437/additional/large/99998437-1.jpg", true));
            tissot.add(new Photo("https://d1rkccsb0jf1bk.cloudfront.net/products/99998437/main/large/t106_417_11_051_00-1460379836-2948.jpg", true));
            rolex.add(new Photo("https://i.insider.com/5f4fbfb97ed0ee001e25d021?width=700&format=jpeg&auto=webp", true));
            rolex.add(new Photo("https://i.insider.com/5f4fbfc1e6ff30001d4e6a13?width=700&format=jpeg&auto=webp", true));
            rolex.add(new Photo("https://i.insider.com/5f4fbfc4e6ff30001d4e6a14?width=700&format=jpeg&auto=webp", true));
            rolex.add(new Photo("https://www.watchtradingco.com/wp-content/uploads/2020/05/WTC_Rolex-Submariner-Date_116610LN_face.jpg", true));
            tagheuer.add(new Photo("https://wfmedia.azureedge.net/imgv2/stock/167670/TagHeuer-Carrera-CV2A10.BA0796-167670-2-200911-154653.jpg;quality=95;w=2000", true));
            tagheuer.add(new Photo("https://wfmedia.azureedge.net/imgv2/stock/167670/TagHeuer-Carrera-CV2A10.BA0796-167670-3-200911-154656.jpg;quality=90;w=800", true));
            tagheuer.add(new Photo("https://wfmedia.azureedge.net/imgv2/stock/167670/TagHeuer-Carrera-CV2A10.BA0796-167670-4-200911-154707.jpg;quality=90;w=800", true));
            tagheuer.add(new Photo("https://wfmedia.azureedge.net/imgv2/stock/167670/TagHeuer-Carrera-CV2A10.BA0796-167670-5-200911-154755.jpg;quality=90;w=800", true));
            omega.add(new Photo("https://wfmedia.azureedge.net/imgv2/stock/167930/Omega-SpeedmasterMoonwatch-311.32.40.30.01.001-167930-1-200828-134105.jpg;quality=95;w=2000", true));
            omega.add(new Photo("https://wfmedia.azureedge.net/imgv2/stock/167930/Omega-SpeedmasterMoonwatch-311.32.40.30.01.001-167930-2-200828-134108.jpg;quality=90;w=800", true));
            omega.add(new Photo("https://wfmedia.azureedge.net/imgv2/stock/167930/Omega-SpeedmasterMoonwatch-311.32.40.30.01.001-167930-3-200828-134112.jpg;quality=90;w=800", true));
            omega.add(new Photo("https://wfmedia.azureedge.net/images/watchfinderimages/media/IT/wf-box-packaging-2020-02-10-09-06-39-517.jpg;quality=90;w=800", true));
            goldenNecklace.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-hardweargraduated-link-necklace-38086766_993595_ED.jpg?&op_usm=1.0,1.0,6.0&$cropN=0.1,0.1,0.8,0.8&defaultImage=NoImageAvailableInternal&", true));
            goldenNecklace.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-hardweargraduated-link-necklace-38086766_1013527_SV_1.jpg?&op_usm=1.0,1.0,6.0&defaultImage=NoImageAvailableInternal&", true));
            goldenNecklace.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-hardweargraduated-link-necklace-38086766_993596_AV_1.jpg?&op_usm=1.0,1.0,6.0&defaultImage=NoImageAvailableInternal&", true));
            goldenNecklace.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-hardweargraduated-link-necklace-38086766_993594_AV_2.jpg?&op_usm=1.0,1.0,6.0&defaultImage=NoImageAvailableInternal&", true));
            goldenPendant.add(new Photo("https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/14410123_1_640.jpg", true));
            goldenPendant.add(new Photo("https://www.goldsmiths.co.uk/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDUzOTU0fGltYWdlL2pwZWd8cHJvZHVjdF9pbWFnZXMvaDJhL2g3MC84OTcyNjc5MTg0NDE0LmpwZ3w0OTg0MmI4YzI4Mjc0ZmRlMDM1MWI2MDBmNzJkNjVjYWU3OWFlNDhlZDI0ZDVmM2JmZjViZDlmNjBmYmQ1ODJh", true));
            goldenPendant.add(new Photo("https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/14240004_1_640.jpg", true));
            goldenPendant.add(new Photo("https://b34959663f5a3997bd0d-2668915a1d3a077262c88fab6aa0aa02.ssl.cf3.rackcdn.com/14240004_2_640.jpg", true));
            diamondVine.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-victoriadiamond-vine-circle-pendant-68287464_1007783_ED.jpg?&op_usm=1.0,1.0,6.0&$cropN=0.1,0.1,0.8,0.8&defaultImage=NoImageAvailableInternal&", true));
            diamondVine.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-victoriadiamond-vine-circle-pendant-68287464_1007784_SV_1.jpg?&op_usm=1.0,1.0,6.0&defaultImage=NoImageAvailableInternal&", true));
            diamondVine.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-victoriadiamond-vine-circle-pendant-68287464_1007781_AV_1.jpg?&op_usm=1.0,1.0,6.0&defaultImage=NoImageAvailableInternal&", true));
            diamondVine.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-victoriadiamond-vine-circle-pendant-68287464_1007782_AV_2.jpg?&op_usm=1.0,1.0,6.0&defaultImage=NoImageAvailableInternal&", true));
            rosePendant.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-tsmile-pendant-35189432_1009333_ED.jpg?&op_usm=1.0,1.0,6.0&$cropN=0.1,0.1,0.8,0.8&defaultImage=NoImageAvailableInternal&", true));
            rosePendant.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-tsmile-pendant-35189432_1009336_SV_1.jpg?&op_usm=1.0,1.0,6.0&defaultImage=NoImageAvailableInternal&", true));
            rosePendant.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-tsmile-pendant-35189432_1009334_AV_1.jpg?&op_usm=1.0,1.0,6.0&defaultImage=NoImageAvailableInternal&", true));
            rosePendant.add(new Photo("https://media.tiffany.com/is/image/Tiffany/EcomItemM/tiffany-tsmile-pendant-35189432_1009335_AV_2.jpg?&op_usm=1.0,1.0,6.0&defaultImage=NoImageAvailableInternal&", true));
            womansTracksuit.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/DV2428_600_600px.jpg", true));
            womansTracksuit.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/DV2428_1_600_600px.jpg", true));
            womansTracksuit.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/DV2428_2_600_600px.jpg", true));
            womansTracksuit.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/DV2428_3_600_600px.jpg", true));
            mensTracksuit.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/FT9183_600_600px.jpg", true));
            mensTracksuit.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/FT9183_1_600_600px.jpg", true));
            mensTracksuit.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/FT9183_2_600_600px.jpg", true));
            mensTracksuit.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/FT9183_3_600_600px.jpg", true));
            womenYoga.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/GH8508_600_600px.jpg", true));
            womenYoga.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/GH8508_1_600_600px.jpg", true));
            womenYoga.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/GH8508_2_600_600px.jpg", true));
            womenYoga.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/GH8508_3_600_600px.jpg", true));
            menShorts.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/FS9809_600_600px.jpg", true));
            menShorts.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/FS9809_1_600_600px.jpg", true));
            menShorts.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/FS9809_2_600_600px.jpg", true));
            menShorts.add(new Photo("https://www.sportvision.ba/files/thumbs/files/images/slike_proizvoda/thumbs_600/FS9809_3_600_600px.jpg", true));
            builtInOven.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/1-34-600x600.png", true));
            builtInOven.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/2-33-600x600.png", true));
            builtInOven.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/3-32-600x600.png", true));
            builtInOven.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/4-27-600x600.png", true));
            microwave.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/04/BryUHuLdcBW-600x600.jpg", true));
            microwave.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/04/M-TehnoMag-10122018-27-1-510Wx510H.jpg", true));
            microwave.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/2-14-600x600.png", true));
            microwave.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/3-13-600x600.png", true));
            dishwasher.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/1-29.png", true));
            dishwasher.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/2-28-600x600.png", true));
            dishwasher.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/3-27-600x600.png", true));
            dishwasher.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/4-22-600x600.png", true));
            washingMachine.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/1-9.jpg", true));
            washingMachine.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/2-9.jpg", true));
            washingMachine.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/3-9.jpg", true));
            washingMachine.add(new Photo("https://www.univerzalno.com/wp-content/uploads/2020/09/4-6.jpg", true));
            suit.add(new Photo("https://cdn.laredoute.com/products/680by680/e/c/3/ec364c782c675119db76ff329451f685.jpg", true));
            suit.add(new Photo("https://cdn.laredoute.com/products/680by680/4/8/6/48602cc569c95065be989ec3de44f715.jpg", true));
            suit.add(new Photo("https://cdn.laredoute.com/products/72by72/a/6/3/a639ff931ef7ccb2f890362133d84788.jpg", true));
            suit.add(new Photo("https://cdn.laredoute.com/products/72by72/6/a/d/6adec2301e7f6c5317a1ce3db7c6dd1a.jpg", true));
            dress.add(new Photo("https://cdn.laredoute.com/products/680by680/6/0/0/600657af954a33bc5c4017d382c25e92.jpg", true));
            dress.add(new Photo("https://cdn.laredoute.com/products/680by680/3/6/6/3668f92978a0da102b563ab6f0eb5816.jpg", true));
            dress.add(new Photo("https://cdn.laredoute.com/products/680by680/4/7/d/47d095e4067c4418202a25d12eb34402.jpg", true));
            dress.add(new Photo("https://cdn.laredoute.com/products/680by680/4/c/5/4c54164bbcdc7969dd20155b64064c4a.jpg", true));
            hats.add(new Photo("https://cdn.laredoute.com/products/680by680/f/9/e/f9ea7e207d6201caacbeb20019c02713.jpg", true));
            hats.add(new Photo("https://cdn.laredoute.com/products/680by680/b/c/d/bcdc719ad621965ca1c1fcea466ef167.jpg", true));
            hats.add(new Photo("https://cdn.laredoute.com/products/680by680/b/5/3/b53d6bda40c0d3b8cadfdc3413597cdd.jpg", true));
            hats.add(new Photo("https://cdn.laredoute.com/products/680by680/5/1/7/517449afd38fa7a194585be2d7f57b78.jpg", true));
            sunglasses.add(new Photo("https://www.inoma.ba/pub/media/catalog/product/cache/image/e9c3970ab036de70892d86c6d221abfe/R/B/RB_3545_186_9A_54_4.jpg", true));
            sunglasses.add(new Photo("https://www.inoma.ba/pub/media/catalog/product/cache/image/e9c3970ab036de70892d86c6d221abfe/R/B/RB_3016_125651_51_4.jpg", true));
            sunglasses.add(new Photo("https://www.inoma.ba/pub/media/catalog/product/cache/image/e9c3970ab036de70892d86c6d221abfe/R/B/RB_3663_002_31_60.jpg", true));
            sunglasses.add(new Photo("https://www.inoma.ba/pub/media/catalog/product/cache/image/e9c3970ab036de70892d86c6d221abfe/R/B/RB_3025_001_51_62_4.jpg", true));
            hammer.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/71%2BsyrfCWRL._AC_SL1500_.jpg", true));
            hammer.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/71MfotiXZ8L._AC_SL1500_.jpg", true));
            hammer.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/81s08j5B4DL._AC_SL1500_.jpg", true));
            hammer.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/81je0SqBxlL._AC_SL1500_.jpg", true));
            cutter.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/71oXQCNXiwL._AC_SL1500_.jpg", true));
            cutter.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/81V0yLooU0L._AC_SL1500_.jpg", true));
            cutter.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/81ZI4TEXu7L._AC_SL1500_.jpg", true));
            cutter.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/71pqPqUIVPL._AC_SL1500_.jpg", true));
            axe.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/71Tt1lg6RxL._AC_SL1500_.jpg", true));
            axe.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/41JXZWrrDEL._AC_.jpg", true));
            axe.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/41GpiCBV76L._AC_.jpg", true));
            axe.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/91zVg6CbIdL._AC_SL1500_.jpg", true));
            saw.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/61x1eu8jLLL._AC_SL1500_.jpg", true));
            saw.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/616hlTv7FOL._AC_SL1500_.jpg", true));
            saw.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/61x1eu8jLLL._AC_SL1500_.jpg", true));
            saw.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/61gohyGcuAL._AC_SL1500_.jpg", true));
            harryPotter.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/A1jGvzIZ7ZL.jpg", true));
            harryPotter.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/91XkoFQSiFL.jpg", true));
            harryPotter.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/41FHillSXYL.jpg", true));
            harryPotter.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/41FHillSXYL.jpg", true));
            theGodfather.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/81IHPwG1tbL.jpg", true));
            theGodfather.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/41LhlqzNVWL.jpg", true));
            theGodfather.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/31sFGTEmtiL.jpg", true));
            theGodfather.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/31sFGTEmtiL.jpg", true));
            lotr.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/8134AkhQJgL.jpg", true));
            lotr.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/81+pnufsEsL.jpg", true));
            lotr.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/31HfU7ZE9YL.jpg", true));
            lotr.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/31HfU7ZE9YL.jpg", true));
            hyperion.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/519b58ZXcEL.jpg", true));
            hyperion.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/51dsDTSIUWL.jpg", true));
            hyperion.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/51UVWoZbFbL.jpg", true));
            hyperion.add(new Photo("https://images-na.ssl-images-amazon.com/images/I/51eL5K6NyJL.jpg", true));

            listOfProducts.add(new Product("Unisex running Shoes", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero. ", 240, new Date(), new Date("2020/11/20"), true, false, "061123456", 240.00, listOfUsers.get(0), runningShoes));
            listOfProducts.add(new Product("Nike running shoes", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 110.00, new Date(), new Date("2019/12/23"), true, false, "061123456", 110.00, listOfUsers.get(3), runningShoes2));
            listOfProducts.add(new Product("Adidas running shoes", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 110.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 110.00, listOfUsers.get(1), runningShoes3));
            listOfProducts.add(new Product("Under armour shoes", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 110.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 110.00, listOfUsers.get(1), runningShoes4));

            listOfProducts.add(new Product("Apple iPhone 11 Pro Max", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero. ", 1999.00, new Date(), new Date("2019/12/16 13:55:12"), true, false, "061123456", 1999.00, listOfUsers.get(3), iPhone11Pro));
            listOfProducts.add(new Product("Apple iPhone X 64GB", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero. ", 1099.99, new Date(), new Date("2020/11/20"), true, false, "061123456", 1099.00, listOfUsers.get(1), iPhoneX));
            listOfProducts.add(new Product("Apple iPhone XR", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero. ", 900.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 900.00, listOfUsers.get(0), iPhoneXr));
            listOfProducts.add(new Product("Samsung Galaxy S20″", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero. ", 1440.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 1440.00, listOfUsers.get(1), s20));

            listOfProducts.add(new Product("HP ProBook G7", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero. ", 1299.95, new Date(), new Date("2020/11/20"), true, false, "061123456", 1299.95, listOfUsers.get(0), hpG7));
            listOfProducts.add(new Product("MacBook Pro 13” ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 2779.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 2779.00, listOfUsers.get(1), macbookPro));
            listOfProducts.add(new Product("Lenovo ThinkPad” ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 1779.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 1779.00, listOfUsers.get(1), lenovo));
            listOfProducts.add(new Product("Dell XPS” ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 1999.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 1999.00, listOfUsers.get(1), dell));

            listOfProducts.add(new Product("Tissot V8", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 4550.99, new Date(), new Date("2020/11/20"), true, false, "061123456", 4550.99, listOfUsers.get(2), tissot));
            listOfProducts.add(new Product("Mens Rolex Submariner", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 10999.99, new Date(), new Date("2020/11/20"), true, false, "061123456", 10999.99, listOfUsers.get(0), rolex));
            listOfProducts.add(new Product("Tag Heuer Carrera", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 4525.99, new Date(), new Date("2020/11/20"), true, false, "061123456", 4525.99, listOfUsers.get(0), tagheuer));
            listOfProducts.add(new Product("Omega Speedmaster", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 9000.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 9000.00, listOfUsers.get(1), omega));

            listOfProducts.add(new Product("Modern woman golden necklace.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 1110.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 1110.00, listOfUsers.get(2), goldenNecklace));
            listOfProducts.add(new Product("Gold pendant", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 1120.00, new Date(), new Date("2019/12/01"), true, false, "061123456", 1120.00, listOfUsers.get(0), goldenPendant));
            listOfProducts.add(new Product("Rose gold pendant", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 1120.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 1120.00, listOfUsers.get(1), rosePendant));
            listOfProducts.add(new Product("Diamond vine", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 1120.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 1120.00, listOfUsers.get(2), diamondVine));

            listOfProducts.add(new Product("Womans tracksuit", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 110.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 110.00, listOfUsers.get(3), womansTracksuit));
            listOfProducts.add(new Product("Mens tracksuit", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 110.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 110.00, listOfUsers.get(0), mensTracksuit));
            listOfProducts.add(new Product("Womans yoga pants", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 110.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 110.00, listOfUsers.get(1), womenYoga));
            listOfProducts.add(new Product("Mens shorts", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 110.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 110.00, listOfUsers.get(2), menShorts));

            listOfProducts.add(new Product("Single bed", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 410.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 410.00, listOfUsers.get(0), bed));
            listOfProducts.add(new Product("King size bed", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 810.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 810.00, listOfUsers.get(3), kingsize));
            listOfProducts.add(new Product("Bed cover", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 90.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 90.00, listOfUsers.get(2), cover));
            listOfProducts.add(new Product("Bunk bed", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 560.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 5600.00, listOfUsers.get(1), bunkbed));

            listOfProducts.add(new Product("Built in oven", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 699.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 699.00, listOfUsers.get(1), builtInOven));
            listOfProducts.add(new Product("Microwave", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 249.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 249.00, listOfUsers.get(2), microwave));
            listOfProducts.add(new Product("Dishwasher", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 499.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 499.00, listOfUsers.get(0), dishwasher));
            listOfProducts.add(new Product("Washing machine", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 599.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 599.00, listOfUsers.get(1), washingMachine));

            listOfProducts.add(new Product("Suit", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 250.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 250.00, listOfUsers.get(0), suit));
            listOfProducts.add(new Product("Woman dress", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 150.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 150.00, listOfUsers.get(2), dress));
            listOfProducts.add(new Product("Hats", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 110.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 110.00, listOfUsers.get(1), hats));
            listOfProducts.add(new Product("Sunglasses", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 149.99, new Date(), new Date("2020/11/20"), true, false, "061123456", 149.99, listOfUsers.get(3), sunglasses));

            listOfProducts.add(new Product("Hammer", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 49.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 49.00, listOfUsers.get(3), hammer));
            listOfProducts.add(new Product("Cutter", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 49.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 49.00, listOfUsers.get(2), cutter));
            listOfProducts.add(new Product("Axe", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 39.99, new Date(), new Date("2020/11/20"), true, false, "061123456", 39.99, listOfUsers.get(1), axe));
            listOfProducts.add(new Product("Saw", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 39.99, new Date(), new Date("2020/11/20"), true, false, "061123456", 39.99, listOfUsers.get(0), saw));

            listOfProducts.add(new Product("Harry Potter", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 60.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 60.00, listOfUsers.get(2), harryPotter));
            listOfProducts.add(new Product("The Godfather", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 60.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 60.00, listOfUsers.get(3), theGodfather));
            listOfProducts.add(new Product("The Lord of the Rings", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 60.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 60.00, listOfUsers.get(1), lotr));
            listOfProducts.add(new Product("Hyperion", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut consequat nulla. Duis nec fermentum erat, et varius augue. Vivamus sed tempor libero.", 60.00, new Date(), new Date("2020/11/20"), true, false, "061123456", 60.00, listOfUsers.get(0), hyperion));


            listOfProducts.get(0).setCategory(shoes);
            listOfProducts.get(0).setSubcategory(subcategory11);
            listOfProducts.get(1).setCategory(shoes);
            listOfProducts.get(1).setSubcategory(subcategory11);
            listOfProducts.get(2).setCategory(shoes);
            listOfProducts.get(2).setSubcategory(subcategory11);
            listOfProducts.get(3).setCategory(shoes);
            listOfProducts.get(3).setSubcategory(subcategory11);
            listOfProducts.get(4).setCategory(mobile);
            listOfProducts.get(4).setSubcategory(subcategory6);
            listOfProducts.get(5).setCategory(mobile);
            listOfProducts.get(5).setSubcategory(subcategory6);
            listOfProducts.get(6).setCategory(mobile);
            listOfProducts.get(6).setSubcategory(subcategory6);
            listOfProducts.get(7).setCategory(mobile);
            listOfProducts.get(7).setSubcategory(subcategory6);
            listOfProducts.get(8).setCategory(computer);
            listOfProducts.get(8).setSubcategory(subcategory7);
            listOfProducts.get(9).setCategory(computer);
            listOfProducts.get(9).setSubcategory(subcategory7);
            listOfProducts.get(10).setCategory(computer);
            listOfProducts.get(10).setSubcategory(subcategory7);
            listOfProducts.get(11).setCategory(computer);
            listOfProducts.get(11).setSubcategory(subcategory7);
            listOfProducts.get(12).setCategory(accessories);
            listOfProducts.get(12).setSubcategory(subcategory8);
            listOfProducts.get(13).setCategory(accessories);
            listOfProducts.get(13).setSubcategory(subcategory8);
            listOfProducts.get(14).setCategory(accessories);
            listOfProducts.get(14).setSubcategory(subcategory8);
            listOfProducts.get(15).setCategory(accessories);
            listOfProducts.get(15).setSubcategory(subcategory8);
            listOfProducts.get(16).setCategory(jewelery);
            listOfProducts.get(16).setSubcategory(subcategory9);
            listOfProducts.get(17).setCategory(jewelery);
            listOfProducts.get(17).setSubcategory(subcategory9);
            listOfProducts.get(18).setCategory(jewelery);
            listOfProducts.get(18).setSubcategory(subcategory9);
            listOfProducts.get(19).setCategory(jewelery);
            listOfProducts.get(19).setSubcategory(subcategory9);
            listOfProducts.get(20).setCategory(sportware);
            listOfProducts.get(20).setSubcategory(subcategory29);
            listOfProducts.get(21).setCategory(sportware);
            listOfProducts.get(21).setSubcategory(subcategory29);
            listOfProducts.get(22).setCategory(sportware);
            listOfProducts.get(22).setSubcategory(subcategory29);
            listOfProducts.get(23).setCategory(sportware);
            listOfProducts.get(23).setSubcategory(subcategory29);
            listOfProducts.get(24).setCategory(home);
            listOfProducts.get(24).setSubcategory(subcategory34);
            listOfProducts.get(25).setCategory(home);
            listOfProducts.get(25).setSubcategory(subcategory34);
            listOfProducts.get(26).setCategory(home);
            listOfProducts.get(26).setSubcategory(subcategory34);
            listOfProducts.get(27).setCategory(home);
            listOfProducts.get(27).setSubcategory(subcategory34);
            listOfProducts.get(28).setCategory(electronics);
            listOfProducts.get(28).setSubcategory(subCategory39);
            listOfProducts.get(29).setCategory(electronics);
            listOfProducts.get(29).setSubcategory(subCategory39);
            listOfProducts.get(30).setCategory(electronics);
            listOfProducts.get(30).setSubcategory(subCategory39);
            listOfProducts.get(31).setCategory(electronics);
            listOfProducts.get(31).setSubcategory(subCategory39);
            listOfProducts.get(32).setCategory(fashion);
            listOfProducts.get(32).setSubcategory(subcategory2);
            listOfProducts.get(33).setCategory(fashion);
            listOfProducts.get(33).setSubcategory(subcategory2);
            listOfProducts.get(34).setCategory(fashion);
            listOfProducts.get(34).setSubcategory(subcategory2);
            listOfProducts.get(35).setCategory(fashion);
            listOfProducts.get(35).setSubcategory(subcategory2);
            listOfProducts.get(36).setCategory(tools);
            listOfProducts.get(36).setSubcategory(subcategory58);
            listOfProducts.get(37).setCategory(tools);
            listOfProducts.get(37).setSubcategory(subcategory58);
            listOfProducts.get(38).setCategory(tools);
            listOfProducts.get(38).setSubcategory(subcategory58);
            listOfProducts.get(39).setCategory(tools);
            listOfProducts.get(39).setSubcategory(subcategory58);
            listOfProducts.get(40).setCategory(books);
            listOfProducts.get(40).setSubcategory(subCategory63);
            listOfProducts.get(41).setCategory(books);
            listOfProducts.get(41).setSubcategory(subCategory63);
            listOfProducts.get(42).setCategory(books);
            listOfProducts.get(42).setSubcategory(subCategory63);
            listOfProducts.get(43).setCategory(books);
            listOfProducts.get(43).setSubcategory(subCategory63);



/*
            listOfProducts.get(0).setPhotos(runningShoes);
            listOfProducts.get(1).setPhotos(runningShoes2);
            listOfProducts.get(2).setPhotos(runningShoes3);
            listOfProducts.get(3).setPhotos(runningShoes4);
            listOfProducts.get(4).setPhotos(iPhone11Pro);
            listOfProducts.get(5).setPhotos(iPhoneX);
            listOfProducts.get(6).setPhotos(iPhoneXr);
            listOfProducts.get(7).setPhotos(s20);
            listOfProducts.get(8).setPhotos(hpG7);
            listOfProducts.get(9).setPhotos(macbookPro);
            listOfProducts.get(10).setPhotos(lenovo);
            listOfProducts.get(11).setPhotos(dell);
            listOfProducts.get(12).setPhotos(tissot);
            listOfProducts.get(13).setPhotos(rolex);
            listOfProducts.get(14).setPhotos(tagheuer);
            listOfProducts.get(15).setPhotos(omega);
            listOfProducts.get(16).setPhotos(goldenNecklace);
            listOfProducts.get(17).setPhotos(goldenPendant);
            listOfProducts.get(18).setPhotos(rosePendant);
            listOfProducts.get(19).setPhotos(diamondVine);
            listOfProducts.get(20).setPhotos(womansTracksuit);
            listOfProducts.get(21).setPhotos(mensTracksuit);
            listOfProducts.get(22).setPhotos(womenYoga);
            listOfProducts.get(23).setPhotos(menShorts);
            listOfProducts.get(24).setPhotos(bed);
            listOfProducts.get(25).setPhotos(kingsize);
            listOfProducts.get(26).setPhotos(cover);
            listOfProducts.get(27).setPhotos(bunkbed);
            listOfProducts.get(28).setPhotos(builtInOven);
            listOfProducts.get(29).setPhotos(microwave);
            listOfProducts.get(30).setPhotos(dishwasher);
            listOfProducts.get(31).setPhotos(washingMachine);
            listOfProducts.get(32).setPhotos(suit);
            listOfProducts.get(33).setPhotos(dress);
            listOfProducts.get(34).setPhotos(hats);
            listOfProducts.get(35).setPhotos(sunglasses);
            listOfProducts.get(36).setPhotos(hammer);
            listOfProducts.get(37).setPhotos(cutter);
            listOfProducts.get(38).setPhotos(axe);
            listOfProducts.get(39).setPhotos(saw);
            listOfProducts.get(40).setPhotos(harryPotter);
            listOfProducts.get(41).setPhotos(theGodfather);
            listOfProducts.get(42).setPhotos(lotr);
            listOfProducts.get(43).setPhotos(hyperion);*/


            productRepository.saveAll(listOfProducts);

        } else {
            LOGGER.log(Level.WARNING, "The data is already persisted.");
        }
    }
}